name: CLA check

on:
  pull_request:
    branches: [master]

jobs:
  cla-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check if Canonical's Contributor License Agreement has been signed
        uses: canonical/has-signed-canonical-cla@19bae73390fdbfdc1ef9a9bb9408d87a1de755f6 # v2
