name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
      target_commitish:
        description: |
          Target commitish (see GH API) for tag creation.
          Can be empty - it will default to the head of the branch it is run from.
        required: false

# To publish assets to on GitHub release pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: stable

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Build
      env:
        TAG_NAME: ${{ inputs.tag_name }}
      run: |
        ./scripts/build.sh --create-tarball --version="${TAG_NAME}"

    - name: Run tests
      run: |
        ./scripts/run-tests.sh

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ inputs.tag_name }}
        TARGET: ${{ inputs.target_commitish || github.ref }}
      run: |
        gh release create "${TAG_NAME}" \
          "anbox-streaming-sdk_${TAG_NAME}.zip" \
          --target "${TARGET}" \
          --title "${TAG_NAME}" \
          --notes "See https://documentation.ubuntu.com/anbox-cloud/reference/release-notes/${TAG_NAME}/ for more information."
